version: "3.6"

services:
  db:
    build:
      context: .

  tests:
    build:
      context: .
    depends_on:
      - db
    environment:
      - PGPASSWORD=pass
    volumes:
      - ./tests:/tests
    command: bash -c 'sleep 1; while !</dev/tcp/db/5432; do sleep 1; done; pg_prove -h db -U test_user -d postgres --ext=".sql" /tests '
