CREATE EXTENSION IF NOT EXISTS "pgtap";

CREATE EXTENSION IF NOT EXISTS "sync" CASCADE;

CREATE SCHEMA "faker";
GRANT USAGE ON SCHEMA "faker" TO PUBLIC;
CREATE EXTENSION IF NOT EXISTS "faker" SCHEMA "faker" CASCADE;
